# content:
# username:
# avatar_url:
tts: false
embeds:
  - title: "GitHub Manager (NodeJS CLI Edition)"
    description: "Version %payload.release.name% (%payload.release.tag_name%) is released and available on:"
    # url:
    color: "2,110,0"
    # footer:
      # text:
      # icon_url:
    # image:
      # url:
    thumbnail:
      url: "https://i.imgur.com/iVfV21H.png"
    # video:
      # url:
    # author:
      # name:
      # url:
      # icon_url:
    fields:
      - name: "GitHub (& Changelog)"
        value: "%payload.release.html_url%"
        inline: false
      - name: "NPM"
        value: "https://www.npmjs.com/package/@hugoalh/github-manager"
        inline: false
      - name: "Repository"
        value: "https://github.com/hugoalh-studio/github-manager-nodejscli"
        inline: false
